name: Quick Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-${{ matrix.python-version }}.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles('requirements-${{ matrix.python-version }}.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-${{ matrix.python-version }}.txt ]; then python -m pip install -r requirements-${{ matrix.python-version }}.txt; fi
        python -m pip install pytest==6.2.1
    - name: Test with pytest
      run: |
        cd tests && python -m pytest -m ci
