name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v2
      env:
          cache-file-name: requirements-${{ matrix.python-version }}.txt
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles(env.cache-file-name) }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ hashFiles(env.cache-file-name) }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        export SKIP_CYTHON=1
        if [ -f requirements-${{ matrix.python-version }}.txt ]; then python -m pip install -r requirements-${{ matrix.python-version }}.txt; fi
        python -m pip install pytest==6.2.1
        python -m pip install pytest-timeout-1.4.2
    - name: Test with pytest
      run: |
        export IN_GITHUB_WORKFLOW=1
        cd tests && bash quick_test.sh &&\
        bash threaded_test.sh &&\
        bash http_test.sh &&\
        bash devices_test.sh
